name: "Build Windows"

on:
  workflow_dispatch:
  push:
    branches:
      - "build/windows"

permissions:
  contents: write

jobs:
  build-windows:
    uses: ./.github/workflows/build.yml
    with:
      platform: "windows-latest"
      target: "x86_64-pc-windows-msvc"
      sign-binaries: false
      upload-artifacts: true
      asset-prefix: "handy"
    secrets: inherit
